/**
 * Shared Constants Library
 *
 * Application-wide constants used across the iForgotPassword ecosystem.
 */

// Export crypto constants
export {
  MIN_PASSWORD_LENGTH,
  RECOMMENDED_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_PBKDF2_ITERATIONS,
  RECOMMENDED_PBKDF2_ITERATIONS,
  SALT_LENGTH,
  ENCRYPTION_KEY_LENGTH,
  IV_LENGTH,
  AUTH_TAG_LENGTH,
} from './crypto';

// Export validation constants
export {
  EMAIL_REGEX,
  MAX_EMAIL_LENGTH,
  MAX_USERNAME_LENGTH,
  MAX_URL_LENGTH,
  MAX_TITLE_LENGTH,
  MAX_NOTES_LENGTH,
  MAX_CUSTOM_FIELD_LENGTH,
  MAX_FOLDER_NAME_LENGTH,
  MAX_DEVICE_NAME_LENGTH,
} from './validation';

// Export API constants
export {
  API_VERSION,
  API_BASE_PATH,
  DEFAULT_PAGINATION_LIMIT,
  MAX_PAGINATION_LIMIT,
  JWT_EXPIRATION,
  JWT_EXPIRATION_SECONDS,
  REFRESH_TOKEN_EXPIRATION,
  REFRESH_TOKEN_EXPIRATION_SECONDS,
  RATE_LIMIT_WINDOW_MS,
  MAX_LOGIN_ATTEMPTS,
  MAX_REGISTRATION_ATTEMPTS,
  MAX_API_REQUESTS,
  ACCOUNT_LOCKOUT_DURATION_MS,
} from './api';
